-- ============================================================
-- PodPal BOT - Production Supabase Database Schema Setup Script
-- Execute this entire script inside your Supabase SQL Editor.
-- ============================================================

-- 1. Bot Configuration Table (Master Kill-Switch & Scope Controls)
create table if not exists public.bot_config (
  id int primary key default 1,
  is_active boolean not null default true,
  chat_scope text not null default 'both' check (chat_scope in ('private_only', 'both')),
  updated_at timestamptz default timezone('utc'::text, now())
);

-- Seed initial master configuration row
insert into public.bot_config (id, is_active, chat_scope)
values (1, true, 'both')
on conflict (id) do nothing;

-- 2. WhatsApp Baileys Auth Store (Zero-cost persistent sessions)
create table if not exists public.whatsapp_auth (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz default timezone('utc'::text, now())
);

-- 3. Knowledge Base Entries & Link Index Table
create table if not exists public.knowledge_entries (
  id bigint generated by default as identity primary key,
  source_type text not null default 'faq', -- 'teams_transcript', 'whatsapp_qa', 'course_guideline', 'link'
  course_name text not null default 'General', -- 'MIT', 'Wadhwani', 'Ethiopia AI', 'General'
  content text not null,
  link_url text,
  created_at timestamptz default timezone('utc'::text, now())
);

-- 4. Scheduled Group Reminders Table (Admin Private DM Scheduler)
create table if not exists public.scheduled_reminders (
  id bigint generated by default as identity primary key,
  creator_jid text not null,
  group_jid text not null default 'all',
  title text not null,
  reminder_type text not null default 'meeting', -- 'meeting', 'deadline'
  scheduled_for timestamptz not null,
  offsets integer[] not null default '{30, 5}', -- Minutes before event (e.g. 30m & 5m or 720m & 60m)
  sent_offsets integer[] default '{}',
  status text not null default 'pending', -- 'pending', 'completed', 'cancelled'
  created_at timestamptz default timezone('utc'::text, now())
);

-- 5. Unresolved Questions Table (Log on Miss)
create table if not exists public.unresolved_queries (
  id bigint generated by default as identity primary key,
  question text not null,
  sender_jid text,
  asked_at timestamptz default timezone('utc'::text, now()),
  is_resolved boolean default false
);

-- 6. Document Catalog Table (Dynamic Document Registry & Context Matching)
create table if not exists public.document_catalog (
  id bigint generated by default as identity primary key,
  doc_key text unique not null,
  title text not null,
  file_name text not null,
  drive_file_id text,
  keywords text[] not null,
  category text default 'General',
  is_available boolean default true,
  description text,
  created_at timestamptz default timezone('utc'::text, now())
);

-- Enable Supabase Realtime for live WebSocket synchronization
alter publication supabase_realtime add table public.bot_config;
alter publication supabase_realtime add table public.scheduled_reminders;
alter publication supabase_realtime add table public.document_catalog;
